/******************************************************************************/
/***         Generated by IBExpert 2020.4.21.2 11/03/2022 19:28:17          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET CLIENTLIB 'C:\Program Files (x86)\Firebird\Firebird_3_0\fbclient.dll';

CREATE DATABASE 'localhost/3050:C:\iFood\BancoDados.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252 COLLATION WIN_PTBR;



/******************************************************************************/
/***                                Domains                                 ***/
/******************************************************************************/

CREATE DOMAIN D_ANO AS
VARCHAR(4);

CREATE DOMAIN D_APLICACAO AS
VARCHAR(1100);

CREATE DOMAIN D_BAIRRO AS
VARCHAR(30)
COLLATE WIN1252;

CREATE DOMAIN D_BARRAS AS
VARCHAR(14);

CREATE DOMAIN D_CAMINHO AS
VARCHAR(255);

CREATE DOMAIN D_CEP AS
VARCHAR(8)
COLLATE WIN1252;

CREATE DOMAIN D_CEST AS
CHAR(7);

CREATE DOMAIN D_CIDADE AS
VARCHAR(30)
COLLATE WIN1252;

CREATE DOMAIN D_CNAE AS
VARCHAR(7);

CREATE DOMAIN D_CNPJ AS
VARCHAR(14)
COLLATE WIN1252;

CREATE DOMAIN D_CPF AS
VARCHAR(11)
COLLATE WIN1252;

CREATE DOMAIN D_DATA AS
TIMESTAMP;

CREATE DOMAIN D_DESCRICAO AS
VARCHAR(255);

CREATE DOMAIN D_DESCRICAO_120 AS
VARCHAR(120)
COLLATE WIN1252;

CREATE DOMAIN D_DESCRIPTION AS
VARCHAR(120)
COLLATE WIN1252;

CREATE DOMAIN D_DIA_MES AS
VARCHAR(5);

CREATE DOMAIN D_DIVERSOS AS
VARCHAR(20)
COLLATE WIN1252;

CREATE DOMAIN D_ECF AS
VARCHAR(50);

CREATE DOMAIN D_EMAIL AS
VARCHAR(40)
COLLATE WIN1252;

CREATE DOMAIN D_ENDERECO AS
VARCHAR(60)
COLLATE WIN1252;

CREATE DOMAIN D_ESTADOCIVIL AS
VARCHAR(10);

CREATE DOMAIN D_FISICA_JURIDICA AS
CHAR(1)
CHECK (value in ('F', 'J'));

CREATE DOMAIN D_FONE AS
VARCHAR(11);

CREATE DOMAIN D_GTIN AS
VARCHAR(14)
COLLATE WIN1252;

CREATE DOMAIN D_HOMEPAGE AS
VARCHAR(50)
COLLATE WIN1252;

CREATE DOMAIN D_HORA AS
TIME;

CREATE DOMAIN D_IE AS
VARCHAR(14);

CREATE DOMAIN D_IM AS
VARCHAR(14);

CREATE DOMAIN D_INF_ADICIONAL AS
VARCHAR(500);

CREATE DOMAIN D_INTEIRO AS
INTEGER;

CREATE DOMAIN D_LOGIN AS
VARCHAR(20)
COLLATE WIN1252;

CREATE DOMAIN D_LOGRADOURO AS
VARCHAR(70)
COLLATE WIN1252;

CREATE DOMAIN D_NAME AS
VARCHAR(60)
COLLATE WIN1252;

CREATE DOMAIN D_NCM AS
VARCHAR(8);

CREATE DOMAIN D_NOME AS
VARCHAR(50)
COLLATE WIN1252;

CREATE DOMAIN D_NRENDERECO AS
VARCHAR(6);

CREATE DOMAIN D_NRSERIE AS
VARCHAR(100);

CREATE DOMAIN D_N_OU_S AS
VARCHAR(1)
check (value in ('N', 'S'))
COLLATE WIN1252;

CREATE DOMAIN D_OBSERVACAO AS
VARCHAR(10000);

CREATE DOMAIN D_OPERACAO AS
VARCHAR(1)
COLLATE WIN1252;

CREATE DOMAIN D_OPERACAOSECUNDARIA AS
VARCHAR(1)
COLLATE WIN1252;

CREATE DOMAIN D_PASS AS
VARCHAR(120);

CREATE DOMAIN D_PHONE AS
VARCHAR(14);

CREATE DOMAIN D_PLACA AS
VARCHAR(7);

CREATE DOMAIN D_PROTOCOLO AS
VARCHAR(50);

CREATE DOMAIN D_RG AS
VARCHAR(10)
COLLATE WIN1252;

CREATE DOMAIN D_SENHA AS
VARCHAR(20);

CREATE DOMAIN D_SEXO AS
VARCHAR(1)
CHECK (value in ('M', 'F'));

CREATE DOMAIN D_SIGLA AS
VARCHAR(3)
COLLATE WIN1252;

CREATE DOMAIN D_TELEFONE AS
VARCHAR(12)
COLLATE WIN1252;

CREATE DOMAIN D_UF AS
VARCHAR(2)
COLLATE WIN1252;

CREATE DOMAIN D_VALOR AS
NUMERIC(15,4)
DEFAULT 0;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_CLIENTE_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_CLIENTE_ID TO 30;

CREATE GENERATOR GEN_IFOOD_IMPRESSOES_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_IFOOD_IMPRESSOES_ID TO 0;

CREATE GENERATOR GEN_IFOOD_MOTIVOCANC_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_IFOOD_MOTIVOCANC_ID TO 22;

CREATE GENERATOR GEN_IFOOD_PAGAMENTOS_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_IFOOD_PAGAMENTOS_ID TO 31;

CREATE GENERATOR GEN_IFOOD_PEDIDOSL_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_IFOOD_PEDIDOSL_ID TO 29;

CREATE GENERATOR GEN_IFOOD_PEDIDOS_ITENS_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_IFOOD_PEDIDOS_ITENS_ID TO 5;

CREATE GENERATOR GEN_IFOOD_POLLING_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_IFOOD_POLLING_ID TO 96;

CREATE GENERATOR GEN_IMPRESSORAS_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_IMPRESSORAS_ID TO 0;

CREATE GENERATOR GEN_LOGS_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_LOGS_ID TO 11460;

CREATE GENERATOR GEN_LOJA_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_LOJA_ID TO 16;

CREATE GENERATOR GEN_SEQDELIVERY_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_SEQDELIVERY_ID TO 3;



/******************************************************************************/
/***                           Stored procedures                            ***/
/******************************************************************************/



SET TERM ^ ;

CREATE PROCEDURE SP_ATUALIZANR_GENERATOR (
    POPERACAO D_OPERACAO,
    PNOME D_NOME,
    PNR D_INTEIRO)
RETURNS (
    PVALOR D_INTEIRO)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE SP_GET_SEQDELIVERY (
    PDATA D_DATA)
RETURNS (
    SEQDELIVERY D_INTEIRO)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE SP_STATUS_PEDIDO_POLLING (
    POPERACAO D_INTEIRO,
    PCODIGO D_INTEIRO)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE SP_ZERA_GEN
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE SPPESQUISALOGS (
    POPERACAO D_OPERACAO,
    PDATAINICIAL D_DATA,
    PDATAFINAL D_DATA,
    PTIPOCHAMADA D_INTEIRO)
RETURNS (
    ACAO D_NAME,
    ENVIADO BLOB SUB_TYPE 1 SEGMENT SIZE 16384,
    RECEBIDO BLOB SUB_TYPE 1 SEGMENT SIZE 16384,
    DATAHORA D_DATA,
    NOMESERVICO D_NAME,
    STATUSLOG D_N_OU_S,
    TIPOCHAMADA D_INTEIRO)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE SPPESQUISAPEDIDOSIFOOD (
    POPERACAO D_OPERACAO,
    PDATAINICIAL D_DATA,
    PDATAFINAL D_DATA,
    PNOME D_NAME,
    PSTATUS D_SIGLA,
    PSHORTREFERENCE D_INTEIRO,
    PSEQDELIVERY D_INTEIRO)
RETURNS (
    CDPEDIDO D_INTEIRO,
    CDINTEGRACAO D_INTEIRO,
    CDPEDIDOGCOM D_INTEIRO,
    CHANGEFOR D_VALOR,
    DATAPEDIDO D_DATA,
    DATAACEITE D_DATA,
    DELIVERYDATETIMESTART D_DATA,
    DELIVERYDATETIMEEND D_DATA,
    DELIVERYFEE D_VALOR,
    ISAGENDADO D_N_OU_S,
    REFERENCE D_DESCRIPTION,
    SEQDELIVERY D_INTEIRO,
    STATUSPEDIDO D_SIGLA,
    NOMELOJA D_NAME,
    OBS D_DESCRICAO,
    RESPONSAVELDESCONTO D_NAME,
    SHORTREFERENCE D_DIVERSOS,
    STATUSACEITE D_N_OU_S,
    STATUSCANCELAR D_N_OU_S,
    STATUSENTREGA D_N_OU_S,
    STATUSPEDIDOINTEGRADO D_N_OU_S,
    SUBTOTAL D_VALOR,
    TAXAADICIONAL D_VALOR,
    TIPOENTREGA D_INTEIRO,
    TOTALPRICE D_VALOR,
    VALORDESCONTO D_VALOR,
    BAIRRO D_BAIRRO,
    CDCLIENTE D_INTEIRO,
    CEP D_CEP,
    CIDADE D_ENDERECO,
    COMPLEMENTOENDERECO D_ENDERECO,
    CPF D_CNPJ,
    FONECEL D_PHONE,
    PHONEIFOOD D_DESCRIPTION,
    PHONE_LOCALIZER D_DIVERSOS,
    PONTOREFERENCIA D_LOGRADOURO,
    LOGRADOURO D_ENDERECO,
    NOME D_NAME,
    NRENDERECO D_ENDERECO)
AS
BEGIN
  SUSPEND;
END^






SET TERM ; ^



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE IFOOD_CONFIG (
    AUTHORIZATIONCODE          D_DIVERSOS,
    AUTHORIZATIONCODEVERIFIER  VARCHAR(1500),
    CDCONFIG                   D_INTEIRO NOT NULL,
    DATAABERTURAFECHAMENTO     D_DATA,
    DATAEXPIRACAO              D_DATA,
    IDFECHAMENTOLOJA           D_NAME,
    MOTIVOFECHAMENTO           D_DESCRICAO,
    REFRESHTOKEN               VARCHAR(1500),
    TOKEN                      VARCHAR(1500)
);


CREATE TABLE IFOOD_MOTIVOCANC (
    CDMOTIVOCANC        D_INTEIRO NOT NULL,
    CODIGOCANCELAMENTO  D_INTEIRO NOT NULL,
    MOTIVOCANCELAMENTO  D_DESCRICAO NOT NULL,
    PEDIDOACEITO        D_N_OU_S NOT NULL
);


CREATE TABLE IFOOD_PAGAMENTOS (
    CDPAGAMENTO  D_INTEIRO NOT NULL,
    CDPEDIDO     D_INTEIRO NOT NULL,
    METHOD       D_NAME,
    NAME         D_NAME,
    PREPAID      D_DIVERSOS,
    "TYPE"       D_DIVERSOS,
    "VALUE"      D_VALOR
);


CREATE TABLE IFOOD_PEDIDOS (
    CANCELADOPOR           D_SIGLA,
    CDCLIENTE              D_INTEIRO,
    CDINTEGRACAO           D_INTEIRO,
    CDLOJA_GCONNECT        D_INTEIRO,
    CDPAGAMENTO            D_INTEIRO,
    CDPEDIDO               D_INTEIRO,
    CDPEDIDOGCOM           D_INTEIRO,
    CHANGEFOR              D_VALOR,
    CREATEDAT              D_DESCRIPTION,
    DATAPEDIDO             D_DATA,
    DATAACEITE             D_DATA,
    DELIVERYFEE            D_VALOR,
    DELIVERYDATETIME       D_DATA,
    DELIVERYDATETIMESTART  D_DATA,
    DELIVERYDATETIMEEND    D_DATA,
    ID                     D_DESCRIPTION,
    ISAGENDADO             D_N_OU_S,
    STATUS                 D_SIGLA,
    STATUSPEDIDO           D_SIGLA,
    MODE                   D_DIVERSOS,
    NOMELOJA               D_NAME,
    OBS                    D_DESCRICAO,
    REFERENCE              D_DESCRIPTION,
    RESPONSAVELDESCONTO    D_NAME,
    SEQDELIVERY            D_INTEIRO,
    SHORTREFERENCE         D_DIVERSOS,
    STATUSACEITE           D_N_OU_S,
    STATUSCANCELAR         D_N_OU_S,
    STATUSENTREGA          D_N_OU_S,
    STATUSPEDIDOINTEGRADO  D_N_OU_S,
    SUBTOTAL               D_VALOR,
    TABLEINDOOR            D_DIVERSOS,
    TAXAADICIONAL          D_VALOR,
    TIPOENTREGA            D_INTEIRO,
    TOTALPRICE             D_VALOR,
    VALORDESCONTO          D_VALOR
);


CREATE TABLE IFOOD_PEDIDOS_ITENS (
    ADDITION          D_VALOR,
    CDPEDIDO          D_INTEIRO DEFAULT NULL,
    DISCOUNT          D_VALOR,
    EXTERNALCODE      D_INTEIRO DEFAULT NULL,
    EXTERNALCODE_PAI  D_INTEIRO,
    ISAUXILIAR        D_N_OU_S,
    NAME              D_DESCRIPTION,
    NRITEM            D_INTEIRO DEFAULT NULL,
    OBSERVATIONS      D_DESCRICAO,
    PRICE             D_VALOR,
    QUANTITY          D_INTEIRO,
    SEQ               D_INTEIRO,
    STATUSINTEGRADO   D_N_OU_S,
    TOTALPRICE        D_VALOR
);


CREATE TABLE IFOOD_POLLING (
    CODIGO                  D_INTEIRO NOT NULL,
    ID                      CHAR(40),
    CODE                    CHAR(20),
    CREATEDAT               CHAR(30),
    DT_HR_SIS               TIMESTAMP,
    INTEGRADO               D_N_OU_S,
    ORDERID                 CHAR(40),
    STATUSACKENVIADO        D_N_OU_S,
    STATUSPEDIDOACEITO      D_N_OU_S,
    STATUSPEDIDOCANCELADO   D_N_OU_S,
    STATUSPEDIDOCONFIRMADO  D_N_OU_S,
    STATUSPEDIDORETIRADO    D_N_OU_S
);


CREATE TABLE IMPRESSORAS (
    "BUFFER"           D_INTEIRO,
    CDIMPRESSORA       D_INTEIRO NOT NULL,
    COLUNAS            D_INTEIRO,
    CONTROLEPORTA      D_N_OU_S,
    CORTARPAPEL        D_N_OU_S,
    ESPACOENTRELINHAS  D_INTEIRO,
    HOST               D_ENDERECO,
    IGNORARTAGS        D_N_OU_S,
    LINHASPULAR        D_INTEIRO,
    MODELO             D_INTEIRO,
    PAGCODIGO          D_INTEIRO,
    PARAMSSTRING       D_DIVERSOS,
    PORTA              D_NAME,
    SETOR              D_DIVERSOS NOT NULL,
    STATUSATIVO        D_N_OU_S,
    TRADUZIRTAGS       D_N_OU_S
);


CREATE TABLE LOGS (
    CDLOGS       INTEGER NOT NULL,
    CDPEDIDO     D_INTEIRO,
    ACAO         D_NAME NOT NULL,
    ENVIADO      BLOB SUB_TYPE 1 SEGMENT SIZE 16384,
    RECEBIDO     BLOB SUB_TYPE 1 SEGMENT SIZE 16384,
    DATAHORA     D_DATA NOT NULL,
    NOMESERVICO  D_NAME,
    TIPOCHAMADA  D_INTEIRO,
    STATUSLOG    D_N_OU_S
);


CREATE TABLE LOJA (
    CDLOJA               D_INTEIRO NOT NULL,
    CDLOJA_GCONNECT      D_INTEIRO,
    ID                   D_DESCRICAO,
    NOMECORPORACAO       D_DESCRICAO,
    NOMELOJA             D_DESCRICAO,
    STATUSLOJAPRINCIPAL  D_N_OU_S
);


CREATE TABLE MUNICIPIOS (
    CDMUNICIPIO    D_INTEIRO NOT NULL,
    NRUF           D_UF,
    NOMEMUNICIPIO  D_NOME
);


CREATE TABLE TB_CLIENTE (
    ALTERACAO              D_DATA,
    ANONASCIMENTO          D_ANO,
    BAIRRO                 D_ENDERECO,
    CDCLIENTE              D_INTEIRO NOT NULL,
    CDESTADOCIVIL          D_INTEIRO,
    CDMUNICIPIO            D_INTEIRO,
    CDREGIAO               D_INTEIRO,
    CDUF                   D_UF,
    CDUFRG                 D_UF,
    CEP                    D_CEP,
    CIDADE                 D_ENDERECO,
    CNPJ                   D_CNPJ,
    COMPLEMENTOENDERECO    D_ENDERECO,
    CPF                    D_CNPJ,
    DATAEXPEDICAORG        D_DATA,
    DIAMESCASAMENTO        D_DIA_MES,
    DIAMESNASCIMENTO       D_DIA_MES,
    DIAVENCIMENTO          D_INTEIRO,
    EMAIL                  D_EMAIL,
    FISICA_JURIDICA        D_FISICA_JURIDICA,
    FONECEL                D_PHONE,
    FONEFAX                D_PHONE,
    FONEFIXO               D_PHONE,
    FONEIFOOD              D_DESCRIPTION,
    GERENCIACREDITO        D_N_OU_S,
    HOMEPAGE               D_HOMEPAGE,
    IDIFOOD                D_INTEIRO,
    IE                     D_IE,
    IM                     D_IM,
    LATITUDE               D_DIVERSOS,
    LONGITUDE              D_DIVERSOS,
    LOGRADOURO             D_ENDERECO,
    NOME                   D_NAME,
    NRENDERECO             D_ENDERECO,
    OBSERVACAO             D_OBSERVACAO,
    ORGAOEXPEDIDORRG       D_DIVERSOS,
    PHONE_LOCALIZER        D_DIVERSOS,
    PONTOREFERENCIA        D_LOGRADOURO,
    RAZAOSOCIAL            D_NAME,
    RG                     D_RG,
    SEXO                   D_SEXO,
    STATUSCLIENTEALTERADO  D_N_OU_S,
    STATUSCLIENTEENVIADO   D_N_OU_S,
    STATUSATIVO            D_N_OU_S,
    UUIDIFOOD              D_DESCRIPTION,
    VALORLIMITE            D_VALOR
);


CREATE TABLE TB_PRODUTO (
    CDCOLECAO                   D_INTEIRO,
    CDCOR                       D_INTEIRO,
    CDFABRICANTE                D_GTIN,
    CDFORNECEDOR                D_INTEIRO,
    CDINTERNO                   D_GTIN,
    CDGRUPO                     D_INTEIRO,
    CDMARCA                     D_INTEIRO,
    CDMATERIAL                  D_INTEIRO,
    CDPRODUTO                   D_INTEIRO NOT NULL,
    CDPRODUTOTRIBUTOS           D_INTEIRO,
    CDSUBGRUPO                  D_INTEIRO,
    CDTAMANHO                   D_INTEIRO,
    CDTRIBUTACAO                D_INTEIRO,
    CDUNIDADEMEDIDA             D_INTEIRO,
    CEST                        D_CEST,
    COMPLEMENTOADICIONAL01      D_APLICACAO,
    COMPLEMENTOADICIONAL01QTDE  D_INTEIRO,
    COMPLEMENTOADICIONAL02      D_APLICACAO,
    COMPLEMENTOADICIONAL02QTDE  D_INTEIRO,
    COMPLEMENTOADICIONAL03      D_APLICACAO,
    COMPLEMENTOADICIONAL03QTDE  D_INTEIRO,
    COMPLEMENTOADICIONAL04      D_APLICACAO,
    COMPLEMENTOADICIONAL04QTDE  D_INTEIRO,
    DATAALTERACAOPRECO          D_DATA,
    DESCRICAOBASE               D_DESCRIPTION,
    DESCRICAO                   D_DESCRIPTION,
    EXTIPI                      D_SIGLA,
    GTIN                        D_GTIN,
    INGREDIENTE                 D_APLICACAO,
    ISAUXPRODUTO                D_N_OU_S,
    ISBORDA                     D_N_OU_S,
    ISMAINPRODUTO               D_N_OU_S,
    ISREGIAO                    D_N_OU_S,
    FRETEIPIOUTROS              D_VALOR,
    LOCALESTOQUE                D_DESCRICAO,
    MARGEMLUCRO                 D_VALOR,
    MODELO                      D_DESCRICAO,
    NCM                         D_NCM,
    OBSERVACAO                  D_OBSERVACAO,
    PEDEBORDA                   D_N_OU_S,
    PRECOANTERIORVENDA          D_VALOR,
    PRECOCOMPRA                 D_VALOR,
    PRECOCUSTO                  D_VALOR,
    PRECOFINALVENDA             D_VALOR,
    PRODBLOQDESCONTO            D_N_OU_S,
    PRODUCAOCOPA                D_N_OU_S,
    PRODUCAOCOZINHA             D_N_OU_S,
    PRODUTOCOMPOSTO             D_N_OU_S,
    QUANTIDADEESTOQUEMINIMO     D_VALOR,
    REQUERADICIONAL             D_N_OU_S,
    STATUSATIVO                 D_N_OU_S,
    STATUSOPCAOMENU             D_N_OU_S,
    STATUSPERFILTRIBUTARIO      D_N_OU_S,
    STATUSPRODUTOSELECIONADO    D_N_OU_S,
    USABALANCA                  D_N_OU_S,
    USACOMPLEMENTOS             D_N_OU_S,
    USAGRUPOADCPRO              D_N_OU_S,
    VALORDESCONTOVENDA          D_VALOR,
    VALORPERCENTUALCOMISSAO     D_VALOR,
    VALORPERCENTUALDESCONTO     D_VALOR
);


CREATE TABLE TB_PRODUTOS_ADC (
    CDOPCAOPRODUTO    D_INTEIRO,
    CDPRODADC         D_INTEIRO NOT NULL,
    CDPRODUTO         D_INTEIRO NOT NULL,
    CDGRUPOADC        D_INTEIRO NOT NULL,
    DESCRICAOPRODUTO  D_DESCRIPTION,
    ORDEMPRODADC      D_INTEIRO NOT NULL,
    PRECOFINALVENDA   D_VALOR
);


CREATE TABLE TB_PRODUTOS_GRUPO_ADC (
    CDGRUPOADC                D_INTEIRO NOT NULL,
    CDPRODUTO                 D_INTEIRO NOT NULL,
    DESC_CATEGORIA_ADICIONAL  D_DESCRIPTION,
    EOBRIGATORIO              D_N_OU_S NOT NULL,
    ORDEMGRUPOADC             D_INTEIRO NOT NULL,
    ORIENTACAO_ADICIONAL      D_DESCRIPTION,
    QTDEMIN                   D_INTEIRO NOT NULL,
    QTDEMAX                   D_INTEIRO NOT NULL,
    STATUSATIVO               D_N_OU_S NOT NULL
);


CREATE TABLE TERMINAL (
    CDEMPRESA            D_INTEIRO,
    CDTERMINAL           D_INTEIRO NOT NULL,
    NOMETERMINAL         D_NOME,
    STATUSATIVOTERMINAL  D_N_OU_S,
    STATUSATUALIZAR      D_N_OU_S,
    STATUSCAIXAENVIAR    D_N_OU_S,
    STATUSCLIENTEENVIAR  D_N_OU_S,
    STATUSVENDAENVIAR    D_N_OU_S
);


CREATE TABLE UF (
    CDUF     VARCHAR(30) NOT NULL,
    NOMEUF   VARCHAR(30),
    SIGLAUF  D_UF
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE IFOOD_CONFIG ADD CONSTRAINT PK_IFOOD_CONFIG PRIMARY KEY (CDCONFIG);
ALTER TABLE IFOOD_MOTIVOCANC ADD CONSTRAINT PK_IFOOD_MOTIVOCANC PRIMARY KEY (CDMOTIVOCANC);
ALTER TABLE IFOOD_PAGAMENTOS ADD CONSTRAINT PK_IFOOD_PAGAMENTOS PRIMARY KEY (CDPAGAMENTO);
ALTER TABLE IFOOD_POLLING ADD PRIMARY KEY (CODIGO);
ALTER TABLE IMPRESSORAS ADD CONSTRAINT PK_IMPRESSORAS PRIMARY KEY (CDIMPRESSORA);
ALTER TABLE LOGS ADD CONSTRAINT PK_LOGS PRIMARY KEY (CDLOGS);
ALTER TABLE LOJA ADD CONSTRAINT PK_LOJA PRIMARY KEY (CDLOJA);
ALTER TABLE MUNICIPIOS ADD CONSTRAINT PK_CDMUNICIPIO PRIMARY KEY (CDMUNICIPIO);
ALTER TABLE TB_CLIENTE ADD CONSTRAINT PKCDCLIENTE PRIMARY KEY (CDCLIENTE);
ALTER TABLE TB_PRODUTO ADD CONSTRAINT PKCDPRODUTO PRIMARY KEY (CDPRODUTO);
ALTER TABLE UF ADD CONSTRAINT PK_UF PRIMARY KEY (CDUF);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX IFOOD_PEDIDOS_DP ON IFOOD_PEDIDOS (DATAPEDIDO);
CREATE INDEX IFOOD_PEDIDOS_REF ON IFOOD_PEDIDOS (REFERENCE);
CREATE INDEX IFOOD_PEDIDOS_SP ON IFOOD_PEDIDOS (STATUSPEDIDO);
CREATE INDEX IFOOD_PEDIDOS_SQ ON IFOOD_PEDIDOS (SEQDELIVERY);
CREATE INDEX IFOOD_POLLING_IDX1 ON IFOOD_POLLING (INTEGRADO);
CREATE INDEX IFOOD_POLLING_IDX2 ON IFOOD_POLLING (CODE);
CREATE INDEX IFOOD_POLLING_IDX3 ON IFOOD_POLLING (DT_HR_SIS);
CREATE INDEX IFOOD_POLLING_IDX4 ON IFOOD_POLLING (ID);
CREATE INDEX IFOOD_POLLING_IDX5 ON IFOOD_POLLING (STATUSACKENVIADO);
CREATE INDEX LOGS_IDX_CDPEDIDO ON LOGS (CDPEDIDO);
CREATE INDEX LOGS_IDX_DATAHORA ON LOGS (DATAHORA);
CREATE INDEX TB_CLIENTE_IDX1 ON TB_CLIENTE (NOME);
CREATE INDEX TB_CLIENTE_IDX2 ON TB_CLIENTE (CPF);
CREATE INDEX TB_CLIENTE_IDX3 ON TB_CLIENTE (CNPJ);
CREATE INDEX TB_CLIENTE_IDX4 ON TB_CLIENTE (IDIFOOD);
CREATE INDEX TB_PRODUTO_IDX ON TB_PRODUTO (DESCRICAO);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: GERACDCLIENTE */
CREATE TRIGGER GERACDCLIENTE FOR TB_CLIENTE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CDCLIENTE IS NULL) THEN
    NEW.CDCLIENTE = GEN_ID(GEN_CLIENTE_ID, 1) ;

END
^


/* Trigger: IFOOD_MOTIVOCANC_BI */
CREATE TRIGGER IFOOD_MOTIVOCANC_BI FOR IFOOD_MOTIVOCANC
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.cdmotivocanc is null) then
    new.cdmotivocanc = gen_id(gen_ifood_motivocanc_id,1);
end
^


/* Trigger: IFOOD_PAGAMENTOS_BI */
CREATE TRIGGER IFOOD_PAGAMENTOS_BI FOR IFOOD_PAGAMENTOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.cdpagamento is null) then
    new.cdpagamento = gen_id(gen_ifood_pagamentos_id,1);
end
^


/* Trigger: IFOOD_PEDIDOS_BI */
CREATE TRIGGER IFOOD_PEDIDOS_BI FOR IFOOD_PEDIDOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.cdpedido is null) then
    new.cdpedido = gen_id(GEN_IFOOD_PEDIDOSL_ID,1);
end
^


/* Trigger: IFOOD_PEDIDOS_ITENS_BI */
CREATE TRIGGER IFOOD_PEDIDOS_ITENS_BI FOR IFOOD_PEDIDOS_ITENS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.seq is null) then
    new.seq = gen_id(gen_ifood_pedidos_itens_id,1);
end
^


/* Trigger: IFOOD_POLLING_BI */
CREATE TRIGGER IFOOD_POLLING_BI FOR IFOOD_POLLING
ACTIVE BEFORE INSERT POSITION 0
as
begin
  new.codigo = gen_id(gen_ifood_polling_id,1);
end
^


/* Trigger: IMPRESSORAS_BI */
CREATE TRIGGER IMPRESSORAS_BI FOR IMPRESSORAS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.cdimpressora is null) then
    new.cdimpressora = gen_id(gen_impressoras_id,1);
end
^


/* Trigger: LOGS_BI */
CREATE TRIGGER LOGS_BI FOR LOGS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.cdlogs is null) then
    new.cdlogs = gen_id(gen_logs_id,1);

  new.datahora = current_timestamp;
end
^


/* Trigger: LOJA_BI */
CREATE TRIGGER LOJA_BI FOR LOJA
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.cdloja is null) then
    new.cdloja = gen_id(gen_loja_id,1);
end
^

SET TERM ; ^



/******************************************************************************/
/***                           Stored procedures                            ***/
/******************************************************************************/



SET TERM ^ ;

ALTER PROCEDURE SP_ATUALIZANR_GENERATOR (
    POPERACAO D_OPERACAO,
    PNOME D_NOME,
    PNR D_INTEIRO)
RETURNS (
    PVALOR D_INTEIRO)
AS
declare variable VSTM varchar(500);
BEGIN
  IF (:POPERACAO = 'A') THEN
  --SE A OPERAÃ‡ÃƒO FOR IGUAL A "A" ENTÃƒO DOU ATUALIZO O GENERATOR
  BEGIN
    VSTM = 'SET GENERATOR ' || PNOME || ' TO ' || PNR;
    EXECUTE STATEMENT VSTM;
  END
  ELSE
    IF (:POPERACAO = 'S') THEN
    --SE A OPERAÃ‡ÃƒO FOR IGUAL A "S" PEGO VALOR DO GENERATOR ATUAL
    BEGIN
      VSTM = 'SELECT GEN_ID(' || PNOME || ',0) PVALOR FROM RDB$DATABASE';
      EXECUTE STATEMENT VSTM INTO :PVALOR;
      SUSPEND;
    END
END^


ALTER PROCEDURE SP_GET_SEQDELIVERY (
    PDATA D_DATA)
RETURNS (
    SEQDELIVERY D_INTEIRO)
AS
declare variable VSTM varchar(500);
declare variable VCDPEDIDO D_INTEIRO;
begin

  for select max(i.cdpedido)
      from ifood_pedidos i
      where i.datapedido > :pdata
      into
        VCDPEDIDO
  do

  if (VCDPEDIDO is null) then
  begin

    VSTM = 'SET GENERATOR GEN_IFOOD_PEDIDOS_ITENS_ID TO 0;';
    EXECUTE STATEMENT VSTM;

    VSTM = 'SET GENERATOR GEN_SEQDELIVERY_ID TO 0;';
    EXECUTE STATEMENT VSTM;

    SEQDELIVERY = GEN_ID(GEN_SEQDELIVERY_ID, 1);

    suspend;
  end
  else begin
    SEQDELIVERY = GEN_ID(GEN_SEQDELIVERY_ID, 1);

    suspend;
  end

end^


ALTER PROCEDURE SP_STATUS_PEDIDO_POLLING (
    POPERACAO D_INTEIRO,
    PCODIGO D_INTEIRO)
AS
begin
  --pedidos novos que chegam no polling
  if (:poperacao = 0) then
  begin
    update ifood_polling p set
    p.integrado = 'S'
    where p.codigo = :pcodigo;
  end
  --pedidos que sao aceitos no ifood
  if (:poperacao = 1) then
  begin
    update ifood_polling p set
    p.statuspedidoaceito = 'S'
    where p.codigo = :pcodigo;
  end
  --pedidos que sao cancelados no ifood
  if (:poperacao = 2) then
  begin
    update ifood_polling p set
    p.statuspedidocancelado = 'S'
    where p.codigo = :pcodigo;
  end
  --pedidos que sao finalizados no ifood
  if (:poperacao = 3) then
  begin
    update ifood_polling p set
    p.statuspedidoconfirmado = 'S'
    where p.codigo = :pcodigo;
  end

  --pedidos que sao retirados no ifood
  if (:poperacao = 4) then
  begin
    update ifood_polling p set
    p.statuspedidoretirado = 'S'
    where p.codigo = :pcodigo;
  end

end^


ALTER PROCEDURE SP_ZERA_GEN
AS
declare variable VSTM varchar(500);
BEGIN
  VSTM = 'SET GENERATOR GEN_NRENTREGA_ID TO 0;';
  EXECUTE STATEMENT VSTM;

  VSTM = 'SET GENERATOR GEN_SENHAPAINEL_ID TO 0;';
  EXECUTE STATEMENT VSTM;
END^


ALTER PROCEDURE SPPESQUISALOGS (
    POPERACAO D_OPERACAO,
    PDATAINICIAL D_DATA,
    PDATAFINAL D_DATA,
    PTIPOCHAMADA D_INTEIRO)
RETURNS (
    ACAO D_NAME,
    ENVIADO BLOB SUB_TYPE 1 SEGMENT SIZE 16384,
    RECEBIDO BLOB SUB_TYPE 1 SEGMENT SIZE 16384,
    DATAHORA D_DATA,
    NOMESERVICO D_NAME,
    STATUSLOG D_N_OU_S,
    TIPOCHAMADA D_INTEIRO)
AS
begin
  if (:POPERACAO = 'T') then
  begin
      for select l.acao,
                 l.enviado,
                 l.recebido,
                 l.datahora,
                 l.nomeservico,
                 l.statuslog,
                 l.tipochamada
          from logs l
          where l.datahora between :pdatainicial and :pdatafinal
          order by l.datahora desc
          into ACAO,
               ENVIADO,
               RECEBIDO,
               DATAHORA,
               NOMESERVICO,
               STATUSLOG,
               TIPOCHAMADA
      do
      suspend;
  end
  if (:POPERACAO = 'S') then
  begin
      for select l.acao,
                 l.enviado,
                 l.recebido,
                 l.datahora,
                 l.nomeservico,
                 l.statuslog,
                 l.tipochamada
          from logs l
          where l.tipochamada = :ptipochamada
          and l.datahora between :pdatainicial and :pdatafinal
          order by l.datahora desc
          into ACAO,
               ENVIADO,
               RECEBIDO,
               DATAHORA,
               NOMESERVICO,
               STATUSLOG,
               TIPOCHAMADA
      do
      suspend;
  end
end^


ALTER PROCEDURE SPPESQUISAPEDIDOSIFOOD (
    POPERACAO D_OPERACAO,
    PDATAINICIAL D_DATA,
    PDATAFINAL D_DATA,
    PNOME D_NAME,
    PSTATUS D_SIGLA,
    PSHORTREFERENCE D_INTEIRO,
    PSEQDELIVERY D_INTEIRO)
RETURNS (
    CDPEDIDO D_INTEIRO,
    CDINTEGRACAO D_INTEIRO,
    CDPEDIDOGCOM D_INTEIRO,
    CHANGEFOR D_VALOR,
    DATAPEDIDO D_DATA,
    DATAACEITE D_DATA,
    DELIVERYDATETIMESTART D_DATA,
    DELIVERYDATETIMEEND D_DATA,
    DELIVERYFEE D_VALOR,
    ISAGENDADO D_N_OU_S,
    REFERENCE D_DESCRIPTION,
    SEQDELIVERY D_INTEIRO,
    STATUSPEDIDO D_SIGLA,
    NOMELOJA D_NAME,
    OBS D_DESCRICAO,
    RESPONSAVELDESCONTO D_NAME,
    SHORTREFERENCE D_DIVERSOS,
    STATUSACEITE D_N_OU_S,
    STATUSCANCELAR D_N_OU_S,
    STATUSENTREGA D_N_OU_S,
    STATUSPEDIDOINTEGRADO D_N_OU_S,
    SUBTOTAL D_VALOR,
    TAXAADICIONAL D_VALOR,
    TIPOENTREGA D_INTEIRO,
    TOTALPRICE D_VALOR,
    VALORDESCONTO D_VALOR,
    BAIRRO D_BAIRRO,
    CDCLIENTE D_INTEIRO,
    CEP D_CEP,
    CIDADE D_ENDERECO,
    COMPLEMENTOENDERECO D_ENDERECO,
    CPF D_CNPJ,
    FONECEL D_PHONE,
    PHONEIFOOD D_DESCRIPTION,
    PHONE_LOCALIZER D_DIVERSOS,
    PONTOREFERENCIA D_LOGRADOURO,
    LOGRADOURO D_ENDERECO,
    NOME D_NAME,
    NRENDERECO D_ENDERECO)
AS
begin
  if (:POPERACAO = 'T') then
  begin
      for select
            t.cdpedido,
            t.cdintegracao,
            t.cdpedidogcom,
            t.changefor,
            t.datapedido,
            t.dataaceite,
            t.deliverydatetimestart,
            t.deliverydatetimeend,
            t.deliveryfee,
            t.isagendado,
            t.reference,
            t.seqdelivery,
            t.statuspedido,
            t.nomeloja,
            t.obs,
            t.responsaveldesconto,
            t.shortreference,
            t.statusaceite,
            t.statuscancelar,
            t.statusentrega,
            t.statuspedidointegrado,
            t.subtotal,
            t.taxaadicional,
            t.tipoentrega,
            t.totalprice,
            t.valordesconto,
            c.bairro,
            c.cdcliente,
            c.cep,
            c.cidade,
            c.complementoendereco,
            c.cpf,
            c.fonecel,
            c.foneifood,
            c.phone_localizer,
            c.logradouro,
            c.nome,
            c.nrendereco,
            c.pontoreferencia
          from ifood_pedidos t
          left join tb_cliente c on t.cdcliente = c.cdcliente
          where t.datapedido between :pdatainicial and :pdatafinal
          and c.nome like '%' || :PNOME || '%'
          order by t.cdpedido desc
          into CDPEDIDO,
               CDINTEGRACAO,
               CDPEDIDOGCOM,
               CHANGEFOR,
               DATAPEDIDO,
               DATAACEITE,
               DELIVERYDATETIMESTART,
               DELIVERYDATETIMEEND,
               DELIVERYFEE,
               ISAGENDADO,
               REFERENCE,
               SEQDELIVERY,
               STATUSPEDIDO,
               NOMELOJA,
               OBS,
               RESPONSAVELDESCONTO,
               SHORTREFERENCE,
               STATUSACEITE,
               STATUSCANCELAR,
               STATUSENTREGA,
               STATUSPEDIDOINTEGRADO,
               SUBTOTAL,
               TAXAADICIONAL,
               TIPOENTREGA,
               TOTALPRICE,
               VALORDESCONTO,
               BAIRRO,
               CDCLIENTE,
               CEP,
               CIDADE,
               COMPLEMENTOENDERECO,
               CPF,
               FONECEL,
               PHONEIFOOD,
               PHONE_LOCALIZER,
               LOGRADOURO,
               NOME,
               NRENDERECO,
               PONTOREFERENCIA
      do
      suspend;
  end
  if (:POPERACAO = 'S') then
  begin
      for select
            t.cdpedido,
            t.cdintegracao,
            t.cdpedidogcom,
            t.changefor,
            t.datapedido,
            t.dataaceite,
            t.deliverydatetimestart,
            t.deliverydatetimeend,
            t.deliveryfee,
            t.isagendado,
            t.reference,
            t.seqdelivery,
            t.statuspedido,
            t.nomeloja,
            t.obs,
            t.responsaveldesconto,
            t.shortreference,
            t.statusaceite,
            t.statuscancelar,
            t.statusentrega,
            t.statuspedidointegrado,
            t.subtotal,
            t.taxaadicional,
            t.tipoentrega,
            t.totalprice,
            t.valordesconto,
            c.bairro,
            c.cdcliente,
            c.cep,
            c.cidade,
            c.complementoendereco,
            c.cpf,
            c.fonecel,
            c.foneifood,
            c.phone_localizer,
            c.logradouro,
            c.nome,
            c.nrendereco,
            c.pontoreferencia
          from ifood_pedidos t
          left join tb_cliente c on t.cdcliente = c.cdcliente
          where t.datapedido between :pdatainicial and :pdatafinal and t.statuspedido = :pstatus
          and c.nome like '%' || :PNOME || '%'
          order by t.cdpedido desc
          into CDPEDIDO,
               CDINTEGRACAO,
               CDPEDIDOGCOM,
               CHANGEFOR,
               DATAPEDIDO,
               DATAACEITE,
               DELIVERYDATETIMESTART,
               DELIVERYDATETIMEEND,
               DELIVERYFEE,
               ISAGENDADO,
               REFERENCE,
               SEQDELIVERY,
               STATUSPEDIDO,
               NOMELOJA,
               OBS,
               RESPONSAVELDESCONTO,
               SHORTREFERENCE,
               STATUSACEITE,
               STATUSCANCELAR,
               STATUSENTREGA,
               STATUSPEDIDOINTEGRADO,
               SUBTOTAL,
               TAXAADICIONAL,
               TIPOENTREGA,
               TOTALPRICE,
               VALORDESCONTO,
               BAIRRO,
               CDCLIENTE,
               CEP,
               CIDADE,
               COMPLEMENTOENDERECO,
               CPF,
               FONECEL,
               PHONEIFOOD,
               PHONE_LOCALIZER,
               LOGRADOURO,
               NOME,
               NRENDERECO,
               PONTOREFERENCIA

      do
      suspend;
  end
  if (:POPERACAO = 'C') then
  begin
      for select
            t.cdpedido,
            t.cdintegracao,
            t.cdpedidogcom,
            t.changefor,
            t.datapedido,
            t.dataaceite,
            t.deliverydatetimestart,
            t.deliverydatetimeend,
            t.deliveryfee,
            t.isagendado,
            t.reference,
            t.seqdelivery,
            t.statuspedido,
            t.nomeloja,
            t.obs,
            t.responsaveldesconto,
            t.shortreference,
            t.statusaceite,
            t.statuscancelar,
            t.statusentrega,
            t.statuspedidointegrado,
            t.subtotal,
            t.taxaadicional,
            t.tipoentrega,
            t.totalprice,
            t.valordesconto,
            c.bairro,
            c.cdcliente,
            c.cep,
            c.cidade,
            c.complementoendereco,
            c.cpf,
            c.fonecel,
            c.foneifood,
            c.phone_localizer,
            c.logradouro,
            c.nome,
            c.nrendereco,
            c.pontoreferencia
          from ifood_pedidos t
          left join tb_cliente c on t.cdcliente = c.cdcliente
          where t.shortreference = :PSHORTREFERENCE
          and c.nome like '%' || :PNOME || '%'
          order by t.cdpedido desc
          into CDPEDIDO,
               CDINTEGRACAO,
               CDPEDIDOGCOM,
               CHANGEFOR,
               DATAPEDIDO,
               DATAACEITE,
               DELIVERYDATETIMESTART,
               DELIVERYDATETIMEEND,
               DELIVERYFEE,
               ISAGENDADO,
               REFERENCE,
               SEQDELIVERY,
               STATUSPEDIDO,
               NOMELOJA,
               OBS,
               RESPONSAVELDESCONTO,
               SHORTREFERENCE,
               STATUSACEITE,
               STATUSCANCELAR,
               STATUSENTREGA,
               STATUSPEDIDOINTEGRADO,
               SUBTOTAL,
               TAXAADICIONAL,
               TIPOENTREGA,
               TOTALPRICE,
               VALORDESCONTO,
               BAIRRO,
               CDCLIENTE,
               CEP,
               CIDADE,
               COMPLEMENTOENDERECO,
               CPF,
               FONECEL,
               PHONEIFOOD,
               PHONE_LOCALIZER,
               LOGRADOURO,
               NOME,
               NRENDERECO,
               PONTOREFERENCIA

      do
      suspend;
  end
  if (:POPERACAO = 'Q') then
  begin
      for select
            t.cdpedido,
            t.cdintegracao,
            t.cdpedidogcom,
            t.changefor,
            t.datapedido,
            t.dataaceite,
            t.deliverydatetimestart,
            t.deliverydatetimeend,
            t.deliveryfee,
            t.isagendado,
            t.reference,
            t.seqdelivery,
            t.statuspedido,
            t.nomeloja,
            t.obs,
            t.responsaveldesconto,
            t.shortreference,
            t.statusaceite,
            t.statuscancelar,
            t.statusentrega,
            t.statuspedidointegrado,
            t.subtotal,
            t.taxaadicional,
            t.tipoentrega,
            t.totalprice,
            t.valordesconto,
            c.bairro,
            c.cdcliente,
            c.cep,
            c.cidade,
            c.complementoendereco,
            c.cpf,
            c.fonecel,
            c.foneifood,
            c.phone_localizer,
            c.logradouro,
            c.nome,
            c.nrendereco,
            c.pontoreferencia
          from ifood_pedidos t
          left join tb_cliente c on t.cdcliente = c.cdcliente
          where t.datapedido between :pdatainicial and :pdatafinal  and t.seqdelivery = :PSEQDELIVERY
          and c.nome like '%' || :PNOME || '%'
          order by t.cdpedido desc
          into CDPEDIDO,
               CDINTEGRACAO,
               CDPEDIDOGCOM,
               CHANGEFOR,
               DATAPEDIDO,
               DATAACEITE,
               DELIVERYDATETIMESTART,
               DELIVERYDATETIMEEND,
               DELIVERYFEE,
               ISAGENDADO,
               REFERENCE,
               SEQDELIVERY,
               STATUSPEDIDO,
               NOMELOJA,
               OBS,
               RESPONSAVELDESCONTO,
               SHORTREFERENCE,
               STATUSACEITE,
               STATUSCANCELAR,
               STATUSENTREGA,
               STATUSPEDIDOINTEGRADO,
               SUBTOTAL,
               TAXAADICIONAL,
               TIPOENTREGA,
               TOTALPRICE,
               VALORDESCONTO,
               BAIRRO,
               CDCLIENTE,
               CEP,
               CIDADE,
               COMPLEMENTOENDERECO,
               CPF,
               FONECEL,
               PHONEIFOOD,
               PHONE_LOCALIZER,
               LOGRADOURO,
               NOME,
               NRENDERECO,
               PONTOREFERENCIA

      do
      suspend;
  end
  if (:POPERACAO = 'X') then
  begin
      for select
            t.cdpedido,
            t.cdintegracao,
            t.cdpedidogcom,
            t.changefor,
            t.datapedido,
            t.dataaceite,
            t.deliverydatetimestart,
            t.deliverydatetimeend,
            t.deliveryfee,
            t.isagendado,
            t.reference,
            t.seqdelivery,
            t.statuspedido,
            t.nomeloja,
            t.obs,
            t.responsaveldesconto,
            t.shortreference,
            t.statusaceite,
            t.statuscancelar,
            t.statusentrega,
            t.statuspedidointegrado,
            t.subtotal,
            t.taxaadicional,
            t.tipoentrega,
            t.totalprice,
            t.valordesconto,
            c.bairro,
            c.cdcliente,
            c.cep,
            c.cidade,
            c.complementoendereco,
            c.cpf,
            c.fonecel,
            c.foneifood,
            c.phone_localizer,
            c.logradouro,
            c.nome,
            c.nrendereco,
            c.pontoreferencia
          from ifood_pedidos t
          left join tb_cliente c on t.cdcliente = c.cdcliente
          where t.datapedido between :pdatainicial and :pdatafinal and t.statuspedido = :pstatus
          order by t.cdpedido desc
          into CDPEDIDO,
               CDINTEGRACAO,
               CDPEDIDOGCOM,
               CHANGEFOR,
               DATAPEDIDO,
               DATAACEITE,
               DELIVERYDATETIMESTART,
               DELIVERYDATETIMEEND,
               DELIVERYFEE,
               ISAGENDADO,
               REFERENCE,
               SEQDELIVERY,
               STATUSPEDIDO,
               NOMELOJA,
               OBS,
               RESPONSAVELDESCONTO,
               SHORTREFERENCE,
               STATUSACEITE,
               STATUSCANCELAR,
               STATUSENTREGA,
               STATUSPEDIDOINTEGRADO,
               SUBTOTAL,
               TAXAADICIONAL,
               TIPOENTREGA,
               TOTALPRICE,
               VALORDESCONTO,
               BAIRRO,
               CDCLIENTE,
               CEP,
               CIDADE,
               COMPLEMENTOENDERECO,
               CPF,
               FONECEL,
               PHONEIFOOD,
               PHONE_LOCALIZER,
               LOGRADOURO,
               NOME,
               NRENDERECO,
               PONTOREFERENCIA
      do
      suspend;
  end
  if (:POPERACAO = 'N') then
  begin
      for select
            t.cdpedido,
            t.cdintegracao,
            t.cdpedidogcom,
            t.changefor,
            t.datapedido,
            t.dataaceite,
            t.deliverydatetimestart,
            t.deliverydatetimeend,
            t.deliveryfee,
            t.isagendado,
            t.reference,
            t.seqdelivery,
            t.statuspedido,
            t.nomeloja,
            t.obs,
            t.responsaveldesconto,
            t.shortreference,
            t.statusaceite,
            t.statuscancelar,
            t.statusentrega,
            t.statuspedidointegrado,
            t.subtotal,
            t.taxaadicional,
            t.tipoentrega,
            t.totalprice,
            t.valordesconto,
            c.bairro,
            c.cdcliente,
            c.cep,
            c.cidade,
            c.complementoendereco,
            c.cpf,
            c.fonecel,
            c.foneifood,
            c.phone_localizer,
            c.logradouro,
            c.nome,
            c.nrendereco,
            c.pontoreferencia
          from ifood_pedidos t
          left join tb_cliente c on t.cdcliente = c.cdcliente
          where t.datapedido between :pdatainicial and :pdatafinal and t.statuspedido = :pstatus
          order by t.cdpedido desc
          into CDPEDIDO,
               CDINTEGRACAO,
               CDPEDIDOGCOM,
               CHANGEFOR,
               DATAPEDIDO,
               DATAACEITE,
               DELIVERYDATETIMESTART,
               DELIVERYDATETIMEEND,
               DELIVERYFEE,
               ISAGENDADO,
               REFERENCE,
               SEQDELIVERY,
               STATUSPEDIDO,
               NOMELOJA,
               OBS,
               RESPONSAVELDESCONTO,
               SHORTREFERENCE,
               STATUSACEITE,
               STATUSCANCELAR,
               STATUSENTREGA,
               STATUSPEDIDOINTEGRADO,
               SUBTOTAL,
               TAXAADICIONAL,
               TIPOENTREGA,
               TOTALPRICE,
               VALORDESCONTO,
               BAIRRO,
               CDCLIENTE,
               CEP,
               CIDADE,
               COMPLEMENTOENDERECO,
               CPF,
               FONECEL,
               PHONEIFOOD,
               PHONE_LOCALIZER,
               LOGRADOURO,
               NOME,
               NRENDERECO,
               PONTOREFERENCIA
      do
      suspend;
  end
end^



SET TERM ; ^
